migration to Azle 0.20.1 with the Express.js approach
dacadeorg/icp-message-board-contract pull request #6
Opened 2024-02-12 08:21 UTC by tarasherasymchuk

2024-02-12 10:13 UTC, Emmanuel-umeh approved these changes
LGTM

2024-02-12 11:52 UTC, Jonath-z approved these changes
LGTM

2024-02-21 12:17 UTC, lastmjs commented
Azle 0.20.2 has been released with a simplified installation experience, I suggest looking at The Azle Book to understand what to change. Mac users may have issues, we're still in the first few days of this change with a couple known problems from users so far.

2024-02-21 12:18 UTC, lastmjs commented
There's also an AUTO_RELOAD environment variable that developers will probably love, you might want to document that

2024-02-21 12:34 UTC, lastmjs requested changes

2024-02-21 12:34 UTC, lastmjs commented on README.md
Please look at the latest changes in The Azle Book and the hello_world of express examples. Azle 0.20.2 introduces a simplified installation experience

2024-02-21 12:34 UTC, lastmjs commented on README.md
> +    "body-parser": "^1.20.2",
You shouldn't need to install body-parser, express.json() or express.text() just works

2024-02-21 12:34 UTC, lastmjs commented on dfx.json
Look at the latest dfx.json files in the hellow_world or other relevant examples, you'll probably want to set candid_gen to http for a quicker compilation time and fewer possibilities for errors during deployment, also take a look at the other new fields

2024-02-21 12:34 UTC, lastmjs commented on src/index.ts
> +import bodyParser from 'body-parser';
Shouldn't need body-parser

2024-02-21 12:34 UTC, lastmjs commented on tsconfig.json
I'm not sure the strict property initialization is needed, don't remember, might want to look into it

2024-02-21 12:34 UTC, lastmjs commented on src/index.ts
> +const messagesStorage = StableBTreeMap<string, Message>(0);
I would recommend declaring this variable with let to indicate mutability, just a subjective best practice I have adopted

2024-02-21 12:34 UTC, lastmjs commented on src/index.ts
> +    app.post("/messages", (req: Request, res: Response) => {
I don't believe it's necessary to put the static types explicitly on each req and res parameter, they are inferred.

2024-02-22 13:35 UTC, merged